/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package gov.pnnl.aristotle.aiminterface;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class NousPathAnswerStreamRecord extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"NousPathAnswerStreamRecord\",\"namespace\":\"gov.pnnl.aristotle.aiminterface\",\"fields\":[{\"name\":\"version\",\"type\":\"int\"},{\"name\":\"uuid\",\"type\":\"string\"},{\"name\":\"timestamp\",\"type\":\"long\"},{\"name\":\"source\",\"type\":\"string\"},{\"name\":\"destination\",\"type\":\"string\"},{\"name\":\"paths\",\"type\":{\"type\":\"array\",\"items\":\"string\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public int version;
  @Deprecated public java.lang.String uuid;
  @Deprecated public long timestamp;
  @Deprecated public java.lang.String source;
  @Deprecated public java.lang.String destination;
  @Deprecated public java.util.List<java.lang.String> paths;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public NousPathAnswerStreamRecord() {}

  /**
   * All-args constructor.
   */
  public NousPathAnswerStreamRecord(java.lang.Integer version, java.lang.String uuid, java.lang.Long timestamp, java.lang.String source, java.lang.String destination, java.util.List<java.lang.String> paths) {
    this.version = version;
    this.uuid = uuid;
    this.timestamp = timestamp;
    this.source = source;
    this.destination = destination;
    this.paths = paths;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return version;
    case 1: return uuid;
    case 2: return timestamp;
    case 3: return source;
    case 4: return destination;
    case 5: return paths;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: version = (java.lang.Integer)value$; break;
    case 1: uuid = value$.toString(); break;
    case 2: timestamp = (java.lang.Long)value$; break;
    case 3: source = value$.toString(); break;
    case 4: destination = value$.toString(); break;
    case 5: paths = (java.util.List<java.lang.String>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'version' field.
   */
  public java.lang.Integer getVersion() {
    return version;
  }

  /**
   * Sets the value of the 'version' field.
   * @param value the value to set.
   */
  public void setVersion(java.lang.Integer value) {
    this.version = value;
  }

  /**
   * Gets the value of the 'uuid' field.
   */
  public java.lang.String getUuid() {
    return uuid;
  }

  /**
   * Sets the value of the 'uuid' field.
   * @param value the value to set.
   */
  public void setUuid(java.lang.String value) {
    this.uuid = value;
  }

  /**
   * Gets the value of the 'timestamp' field.
   */
  public java.lang.Long getTimestamp() {
    return timestamp;
  }

  /**
   * Sets the value of the 'timestamp' field.
   * @param value the value to set.
   */
  public void setTimestamp(java.lang.Long value) {
    this.timestamp = value;
  }

  /**
   * Gets the value of the 'source' field.
   */
  public java.lang.String getSource() {
    return source;
  }

  /**
   * Sets the value of the 'source' field.
   * @param value the value to set.
   */
  public void setSource(java.lang.String value) {
    this.source = value;
  }

  /**
   * Gets the value of the 'destination' field.
   */
  public java.lang.String getDestination() {
    return destination;
  }

  /**
   * Sets the value of the 'destination' field.
   * @param value the value to set.
   */
  public void setDestination(java.lang.String value) {
    this.destination = value;
  }

  /**
   * Gets the value of the 'paths' field.
   */
  public java.util.List<java.lang.String> getPaths() {
    return paths;
  }

  /**
   * Sets the value of the 'paths' field.
   * @param value the value to set.
   */
  public void setPaths(java.util.List<java.lang.String> value) {
    this.paths = value;
  }

  /** Creates a new NousPathAnswerStreamRecord RecordBuilder */
  public static gov.pnnl.aristotle.aiminterface.NousPathAnswerStreamRecord.Builder newBuilder() {
    return new gov.pnnl.aristotle.aiminterface.NousPathAnswerStreamRecord.Builder();
  }
  
  /** Creates a new NousPathAnswerStreamRecord RecordBuilder by copying an existing Builder */
  public static gov.pnnl.aristotle.aiminterface.NousPathAnswerStreamRecord.Builder newBuilder(gov.pnnl.aristotle.aiminterface.NousPathAnswerStreamRecord.Builder other) {
    return new gov.pnnl.aristotle.aiminterface.NousPathAnswerStreamRecord.Builder(other);
  }
  
  /** Creates a new NousPathAnswerStreamRecord RecordBuilder by copying an existing NousPathAnswerStreamRecord instance */
  public static gov.pnnl.aristotle.aiminterface.NousPathAnswerStreamRecord.Builder newBuilder(gov.pnnl.aristotle.aiminterface.NousPathAnswerStreamRecord other) {
    return new gov.pnnl.aristotle.aiminterface.NousPathAnswerStreamRecord.Builder(other);
  }
  
  /**
   * RecordBuilder for NousPathAnswerStreamRecord instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<NousPathAnswerStreamRecord>
    implements org.apache.avro.data.RecordBuilder<NousPathAnswerStreamRecord> {

    private int version;
    private java.lang.String uuid;
    private long timestamp;
    private java.lang.String source;
    private java.lang.String destination;
    private java.util.List<java.lang.String> paths;

    /** Creates a new Builder */
    private Builder() {
      super(gov.pnnl.aristotle.aiminterface.NousPathAnswerStreamRecord.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(gov.pnnl.aristotle.aiminterface.NousPathAnswerStreamRecord.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.version)) {
        this.version = data().deepCopy(fields()[0].schema(), other.version);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.uuid)) {
        this.uuid = data().deepCopy(fields()[1].schema(), other.uuid);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[2].schema(), other.timestamp);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.source)) {
        this.source = data().deepCopy(fields()[3].schema(), other.source);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.destination)) {
        this.destination = data().deepCopy(fields()[4].schema(), other.destination);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.paths)) {
        this.paths = data().deepCopy(fields()[5].schema(), other.paths);
        fieldSetFlags()[5] = true;
      }
    }
    
    /** Creates a Builder by copying an existing NousPathAnswerStreamRecord instance */
    private Builder(gov.pnnl.aristotle.aiminterface.NousPathAnswerStreamRecord other) {
            super(gov.pnnl.aristotle.aiminterface.NousPathAnswerStreamRecord.SCHEMA$);
      if (isValidValue(fields()[0], other.version)) {
        this.version = data().deepCopy(fields()[0].schema(), other.version);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.uuid)) {
        this.uuid = data().deepCopy(fields()[1].schema(), other.uuid);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[2].schema(), other.timestamp);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.source)) {
        this.source = data().deepCopy(fields()[3].schema(), other.source);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.destination)) {
        this.destination = data().deepCopy(fields()[4].schema(), other.destination);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.paths)) {
        this.paths = data().deepCopy(fields()[5].schema(), other.paths);
        fieldSetFlags()[5] = true;
      }
    }

    /** Gets the value of the 'version' field */
    public java.lang.Integer getVersion() {
      return version;
    }
    
    /** Sets the value of the 'version' field */
    public gov.pnnl.aristotle.aiminterface.NousPathAnswerStreamRecord.Builder setVersion(int value) {
      validate(fields()[0], value);
      this.version = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'version' field has been set */
    public boolean hasVersion() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'version' field */
    public gov.pnnl.aristotle.aiminterface.NousPathAnswerStreamRecord.Builder clearVersion() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'uuid' field */
    public java.lang.String getUuid() {
      return uuid;
    }
    
    /** Sets the value of the 'uuid' field */
    public gov.pnnl.aristotle.aiminterface.NousPathAnswerStreamRecord.Builder setUuid(java.lang.String value) {
      validate(fields()[1], value);
      this.uuid = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'uuid' field has been set */
    public boolean hasUuid() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'uuid' field */
    public gov.pnnl.aristotle.aiminterface.NousPathAnswerStreamRecord.Builder clearUuid() {
      uuid = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'timestamp' field */
    public java.lang.Long getTimestamp() {
      return timestamp;
    }
    
    /** Sets the value of the 'timestamp' field */
    public gov.pnnl.aristotle.aiminterface.NousPathAnswerStreamRecord.Builder setTimestamp(long value) {
      validate(fields()[2], value);
      this.timestamp = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'timestamp' field has been set */
    public boolean hasTimestamp() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'timestamp' field */
    public gov.pnnl.aristotle.aiminterface.NousPathAnswerStreamRecord.Builder clearTimestamp() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'source' field */
    public java.lang.String getSource() {
      return source;
    }
    
    /** Sets the value of the 'source' field */
    public gov.pnnl.aristotle.aiminterface.NousPathAnswerStreamRecord.Builder setSource(java.lang.String value) {
      validate(fields()[3], value);
      this.source = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'source' field has been set */
    public boolean hasSource() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'source' field */
    public gov.pnnl.aristotle.aiminterface.NousPathAnswerStreamRecord.Builder clearSource() {
      source = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'destination' field */
    public java.lang.String getDestination() {
      return destination;
    }
    
    /** Sets the value of the 'destination' field */
    public gov.pnnl.aristotle.aiminterface.NousPathAnswerStreamRecord.Builder setDestination(java.lang.String value) {
      validate(fields()[4], value);
      this.destination = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'destination' field has been set */
    public boolean hasDestination() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'destination' field */
    public gov.pnnl.aristotle.aiminterface.NousPathAnswerStreamRecord.Builder clearDestination() {
      destination = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /** Gets the value of the 'paths' field */
    public java.util.List<java.lang.String> getPaths() {
      return paths;
    }
    
    /** Sets the value of the 'paths' field */
    public gov.pnnl.aristotle.aiminterface.NousPathAnswerStreamRecord.Builder setPaths(java.util.List<java.lang.String> value) {
      validate(fields()[5], value);
      this.paths = value;
      fieldSetFlags()[5] = true;
      return this; 
    }
    
    /** Checks whether the 'paths' field has been set */
    public boolean hasPaths() {
      return fieldSetFlags()[5];
    }
    
    /** Clears the value of the 'paths' field */
    public gov.pnnl.aristotle.aiminterface.NousPathAnswerStreamRecord.Builder clearPaths() {
      paths = null;
      fieldSetFlags()[5] = false;
      return this;
    }


    public NousPathAnswerStreamRecord build() {
      try {
        NousPathAnswerStreamRecord record = new NousPathAnswerStreamRecord();
        record.version = fieldSetFlags()[0] ? this.version : (java.lang.Integer) defaultValue(fields()[0]);
        record.uuid = fieldSetFlags()[1] ? this.uuid : (java.lang.String) defaultValue(fields()[1]);
        record.timestamp = fieldSetFlags()[2] ? this.timestamp : (java.lang.Long) defaultValue(fields()[2]);
        record.source = fieldSetFlags()[3] ? this.source : (java.lang.String) defaultValue(fields()[3]);
        record.destination = fieldSetFlags()[4] ? this.destination : (java.lang.String) defaultValue(fields()[4]);
        record.paths = fieldSetFlags()[5] ? this.paths : (java.util.List<java.lang.String>) defaultValue(fields()[5]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
