/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package gov.pnnl.aristotle.aiminterface;  



@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class NousAnswerStreamRecord extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"NousAnswerStreamRecord\",\"namespace\":\"gov.pnnl.aristotle.aiminterface\",\"fields\":[{\"name\":\"version\",\"type\":\"int\"},{\"name\":\"uuid\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"timestamp\",\"type\":\"long\"},{\"name\":\"infobox\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"profile\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}},{\"name\":\"paths\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}},{\"name\":\"company\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"lob\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"score\",\"type\":\"double\"},{\"name\":\"expectedCount\",\"type\":\"long\"},{\"name\":\"examplarCompany\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"probability\",\"type\":\"double\"},{\"name\":\"highScore\",\"type\":\"boolean\"},{\"name\":\"isHighScore\",\"type\":\"boolean\"},{\"name\":\"hscodes\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}},{\"name\":\"recordids\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public int version;
  @Deprecated public java.lang.String uuid;
  @Deprecated public long timestamp;
  @Deprecated public java.lang.String infobox;
  @Deprecated public java.util.List<java.lang.String> profile;
  @Deprecated public java.util.List<java.lang.String> paths;
  @Deprecated public java.lang.String company;
  @Deprecated public java.lang.String lob;
  @Deprecated public double score;
  @Deprecated public long expectedCount;
  @Deprecated public java.lang.String examplarCompany;
  @Deprecated public double probability;
  @Deprecated public boolean highScore;
  @Deprecated public boolean isHighScore;
  @Deprecated public java.util.List<java.lang.String> hscodes;
  @Deprecated public java.util.List<java.lang.String> recordids;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public NousAnswerStreamRecord() {}

  /**
   * All-args constructor.
   */
  public NousAnswerStreamRecord(java.lang.Integer version, java.lang.String uuid, java.lang.Long timestamp, java.lang.String infobox, java.util.List<java.lang.String> profile, java.util.List<java.lang.String> paths, java.lang.String company, java.lang.String lob, java.lang.Double score, java.lang.Long expectedCount, java.lang.String examplarCompany, java.lang.Double probability, java.lang.Boolean highScore, java.lang.Boolean isHighScore, java.util.List<java.lang.String> hscodes, java.util.List<java.lang.String> recordids) {
    this.version = version;
    this.uuid = uuid;
    this.timestamp = timestamp;
    this.infobox = infobox;
    this.profile = profile;
    this.paths = paths;
    this.company = company;
    this.lob = lob;
    this.score = score;
    this.expectedCount = expectedCount;
    this.examplarCompany = examplarCompany;
    this.probability = probability;
    this.highScore = highScore;
    this.isHighScore = isHighScore;
    this.hscodes = hscodes;
    this.recordids = recordids;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return version;
    case 1: return uuid;
    case 2: return timestamp;
    case 3: return infobox;
    case 4: return profile;
    case 5: return paths;
    case 6: return company;
    case 7: return lob;
    case 8: return score;
    case 9: return expectedCount;
    case 10: return examplarCompany;
    case 11: return probability;
    case 12: return highScore;
    case 13: return isHighScore;
    case 14: return hscodes;
    case 15: return recordids;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: version = (java.lang.Integer)value$; break;
    case 1: uuid = (java.lang.String)value$; break;
    case 2: timestamp = (java.lang.Long)value$; break;
    case 3: infobox = (java.lang.String)value$; break;
    case 4: profile = (java.util.List<java.lang.String>)value$; break;
    case 5: paths = (java.util.List<java.lang.String>)value$; break;
    case 6: company = (java.lang.String)value$; break;
    case 7: lob = (java.lang.String)value$; break;
    case 8: score = (java.lang.Double)value$; break;
    case 9: expectedCount = (java.lang.Long)value$; break;
    case 10: examplarCompany = (java.lang.String)value$; break;
    case 11: probability = (java.lang.Double)value$; break;
    case 12: highScore = (java.lang.Boolean)value$; break;
    case 13: isHighScore = (java.lang.Boolean)value$; break;
    case 14: hscodes = (java.util.List<java.lang.String>)value$; break;
    case 15: recordids = (java.util.List<java.lang.String>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'version' field.
   */
  public java.lang.Integer getVersion() {
    return version;
  }

  /**
   * Sets the value of the 'version' field.
   * @param value the value to set.
   */
  public void setVersion(java.lang.Integer value) {
    this.version = value;
  }

  /**
   * Gets the value of the 'uuid' field.
   */
  public java.lang.String getUuid() {
    return uuid;
  }

  /**
   * Sets the value of the 'uuid' field.
   * @param value the value to set.
   */
  public void setUuid(java.lang.String value) {
    this.uuid = value;
  }

  /**
   * Gets the value of the 'timestamp' field.
   */
  public java.lang.Long getTimestamp() {
    return timestamp;
  }

  /**
   * Sets the value of the 'timestamp' field.
   * @param value the value to set.
   */
  public void setTimestamp(java.lang.Long value) {
    this.timestamp = value;
  }

  /**
   * Gets the value of the 'infobox' field.
   */
  public java.lang.String getInfobox() {
    return infobox;
  }

  /**
   * Sets the value of the 'infobox' field.
   * @param value the value to set.
   */
  public void setInfobox(java.lang.String value) {
    this.infobox = value;
  }

  /**
   * Gets the value of the 'profile' field.
   */
  public java.util.List<java.lang.String> getProfile() {
    return profile;
  }

  /**
   * Sets the value of the 'profile' field.
   * @param value the value to set.
   */
  public void setProfile(java.util.List<java.lang.String> value) {
    this.profile = value;
  }

  /**
   * Gets the value of the 'paths' field.
   */
  public java.util.List<java.lang.String> getPaths() {
    return paths;
  }

  /**
   * Sets the value of the 'paths' field.
   * @param value the value to set.
   */
  public void setPaths(java.util.List<java.lang.String> value) {
    this.paths = value;
  }

  /**
   * Gets the value of the 'company' field.
   */
  public java.lang.String getCompany() {
    return company;
  }

  /**
   * Sets the value of the 'company' field.
   * @param value the value to set.
   */
  public void setCompany(java.lang.String value) {
    this.company = value;
  }

  /**
   * Gets the value of the 'lob' field.
   */
  public java.lang.String getLob() {
    return lob;
  }

  /**
   * Sets the value of the 'lob' field.
   * @param value the value to set.
   */
  public void setLob(java.lang.String value) {
    this.lob = value;
  }

  /**
   * Gets the value of the 'score' field.
   */
  public java.lang.Double getScore() {
    return score;
  }

  /**
   * Sets the value of the 'score' field.
   * @param value the value to set.
   */
  public void setScore(java.lang.Double value) {
    this.score = value;
  }

  /**
   * Gets the value of the 'expectedCount' field.
   */
  public java.lang.Long getExpectedCount() {
    return expectedCount;
  }

  /**
   * Sets the value of the 'expectedCount' field.
   * @param value the value to set.
   */
  public void setExpectedCount(java.lang.Long value) {
    this.expectedCount = value;
  }

  /**
   * Gets the value of the 'examplarCompany' field.
   */
  public java.lang.String getExamplarCompany() {
    return examplarCompany;
  }

  /**
   * Sets the value of the 'examplarCompany' field.
   * @param value the value to set.
   */
  public void setExamplarCompany(java.lang.String value) {
    this.examplarCompany = value;
  }

  /**
   * Gets the value of the 'probability' field.
   */
  public java.lang.Double getProbability() {
    return probability;
  }

  /**
   * Sets the value of the 'probability' field.
   * @param value the value to set.
   */
  public void setProbability(java.lang.Double value) {
    this.probability = value;
  }

  /**
   * Gets the value of the 'highScore' field.
   */
  public java.lang.Boolean getHighScore() {
    return highScore;
  }

  /**
   * Sets the value of the 'highScore' field.
   * @param value the value to set.
   */
  public void setHighScore(java.lang.Boolean value) {
    this.highScore = value;
  }

  /**
   * Gets the value of the 'isHighScore' field.
   */
  public java.lang.Boolean getIsHighScore() {
    return isHighScore;
  }

  /**
   * Sets the value of the 'isHighScore' field.
   * @param value the value to set.
   */
  public void setIsHighScore(java.lang.Boolean value) {
    this.isHighScore = value;
  }

  /**
   * Gets the value of the 'hscodes' field.
   */
  public java.util.List<java.lang.String> getHscodes() {
    return hscodes;
  }

  /**
   * Sets the value of the 'hscodes' field.
   * @param value the value to set.
   */
  public void setHscodes(java.util.List<java.lang.String> value) {
    this.hscodes = value;
  }

  /**
   * Gets the value of the 'recordids' field.
   */
  public java.util.List<java.lang.String> getRecordids() {
    return recordids;
  }

  /**
   * Sets the value of the 'recordids' field.
   * @param value the value to set.
   */
  public void setRecordids(java.util.List<java.lang.String> value) {
    this.recordids = value;
  }

  /** Creates a new NousAnswerStreamRecord RecordBuilder */
  public static gov.pnnl.aristotle.aiminterface.NousAnswerStreamRecord.Builder newBuilder() {
    return new gov.pnnl.aristotle.aiminterface.NousAnswerStreamRecord.Builder();
  }
  
  /** Creates a new NousAnswerStreamRecord RecordBuilder by copying an existing Builder */
  public static gov.pnnl.aristotle.aiminterface.NousAnswerStreamRecord.Builder newBuilder(gov.pnnl.aristotle.aiminterface.NousAnswerStreamRecord.Builder other) {
    return new gov.pnnl.aristotle.aiminterface.NousAnswerStreamRecord.Builder(other);
  }
  
  /** Creates a new NousAnswerStreamRecord RecordBuilder by copying an existing NousAnswerStreamRecord instance */
  public static gov.pnnl.aristotle.aiminterface.NousAnswerStreamRecord.Builder newBuilder(gov.pnnl.aristotle.aiminterface.NousAnswerStreamRecord other) {
    return new gov.pnnl.aristotle.aiminterface.NousAnswerStreamRecord.Builder(other);
  }
  
  /**
   * RecordBuilder for NousAnswerStreamRecord instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<NousAnswerStreamRecord>
    implements org.apache.avro.data.RecordBuilder<NousAnswerStreamRecord> {

    private int version;
    private java.lang.String uuid;
    private long timestamp;
    private java.lang.String infobox;
    private java.util.List<java.lang.String> profile;
    private java.util.List<java.lang.String> paths;
    private java.lang.String company;
    private java.lang.String lob;
    private double score;
    private long expectedCount;
    private java.lang.String examplarCompany;
    private double probability;
    private boolean highScore;
    private boolean isHighScore;
    private java.util.List<java.lang.String> hscodes;
    private java.util.List<java.lang.String> recordids;

    /** Creates a new Builder */
    private Builder() {
      super(gov.pnnl.aristotle.aiminterface.NousAnswerStreamRecord.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(gov.pnnl.aristotle.aiminterface.NousAnswerStreamRecord.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.version)) {
        this.version = data().deepCopy(fields()[0].schema(), other.version);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.uuid)) {
        this.uuid = data().deepCopy(fields()[1].schema(), other.uuid);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[2].schema(), other.timestamp);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.infobox)) {
        this.infobox = data().deepCopy(fields()[3].schema(), other.infobox);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.profile)) {
        this.profile = data().deepCopy(fields()[4].schema(), other.profile);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.paths)) {
        this.paths = data().deepCopy(fields()[5].schema(), other.paths);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.company)) {
        this.company = data().deepCopy(fields()[6].schema(), other.company);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.lob)) {
        this.lob = data().deepCopy(fields()[7].schema(), other.lob);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.score)) {
        this.score = data().deepCopy(fields()[8].schema(), other.score);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.expectedCount)) {
        this.expectedCount = data().deepCopy(fields()[9].schema(), other.expectedCount);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.examplarCompany)) {
        this.examplarCompany = data().deepCopy(fields()[10].schema(), other.examplarCompany);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.probability)) {
        this.probability = data().deepCopy(fields()[11].schema(), other.probability);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.highScore)) {
        this.highScore = data().deepCopy(fields()[12].schema(), other.highScore);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.isHighScore)) {
        this.isHighScore = data().deepCopy(fields()[13].schema(), other.isHighScore);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.hscodes)) {
        this.hscodes = data().deepCopy(fields()[14].schema(), other.hscodes);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.recordids)) {
        this.recordids = data().deepCopy(fields()[15].schema(), other.recordids);
        fieldSetFlags()[15] = true;
      }
    }
    
    /** Creates a Builder by copying an existing NousAnswerStreamRecord instance */
    private Builder(gov.pnnl.aristotle.aiminterface.NousAnswerStreamRecord other) {
            super(gov.pnnl.aristotle.aiminterface.NousAnswerStreamRecord.SCHEMA$);
      if (isValidValue(fields()[0], other.version)) {
        this.version = data().deepCopy(fields()[0].schema(), other.version);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.uuid)) {
        this.uuid = data().deepCopy(fields()[1].schema(), other.uuid);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[2].schema(), other.timestamp);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.infobox)) {
        this.infobox = data().deepCopy(fields()[3].schema(), other.infobox);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.profile)) {
        this.profile = data().deepCopy(fields()[4].schema(), other.profile);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.paths)) {
        this.paths = data().deepCopy(fields()[5].schema(), other.paths);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.company)) {
        this.company = data().deepCopy(fields()[6].schema(), other.company);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.lob)) {
        this.lob = data().deepCopy(fields()[7].schema(), other.lob);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.score)) {
        this.score = data().deepCopy(fields()[8].schema(), other.score);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.expectedCount)) {
        this.expectedCount = data().deepCopy(fields()[9].schema(), other.expectedCount);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.examplarCompany)) {
        this.examplarCompany = data().deepCopy(fields()[10].schema(), other.examplarCompany);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.probability)) {
        this.probability = data().deepCopy(fields()[11].schema(), other.probability);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.highScore)) {
        this.highScore = data().deepCopy(fields()[12].schema(), other.highScore);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.isHighScore)) {
        this.isHighScore = data().deepCopy(fields()[13].schema(), other.isHighScore);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.hscodes)) {
        this.hscodes = data().deepCopy(fields()[14].schema(), other.hscodes);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.recordids)) {
        this.recordids = data().deepCopy(fields()[15].schema(), other.recordids);
        fieldSetFlags()[15] = true;
      }
    }

    /** Gets the value of the 'version' field */
    public java.lang.Integer getVersion() {
      return version;
    }
    
    /** Sets the value of the 'version' field */
    public gov.pnnl.aristotle.aiminterface.NousAnswerStreamRecord.Builder setVersion(int value) {
      validate(fields()[0], value);
      this.version = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'version' field has been set */
    public boolean hasVersion() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'version' field */
    public gov.pnnl.aristotle.aiminterface.NousAnswerStreamRecord.Builder clearVersion() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'uuid' field */
    public java.lang.String getUuid() {
      return uuid;
    }
    
    /** Sets the value of the 'uuid' field */
    public gov.pnnl.aristotle.aiminterface.NousAnswerStreamRecord.Builder setUuid(java.lang.String value) {
      validate(fields()[1], value);
      this.uuid = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'uuid' field has been set */
    public boolean hasUuid() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'uuid' field */
    public gov.pnnl.aristotle.aiminterface.NousAnswerStreamRecord.Builder clearUuid() {
      uuid = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'timestamp' field */
    public java.lang.Long getTimestamp() {
      return timestamp;
    }
    
    /** Sets the value of the 'timestamp' field */
    public gov.pnnl.aristotle.aiminterface.NousAnswerStreamRecord.Builder setTimestamp(long value) {
      validate(fields()[2], value);
      this.timestamp = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'timestamp' field has been set */
    public boolean hasTimestamp() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'timestamp' field */
    public gov.pnnl.aristotle.aiminterface.NousAnswerStreamRecord.Builder clearTimestamp() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'infobox' field */
    public java.lang.String getInfobox() {
      return infobox;
    }
    
    /** Sets the value of the 'infobox' field */
    public gov.pnnl.aristotle.aiminterface.NousAnswerStreamRecord.Builder setInfobox(java.lang.String value) {
      validate(fields()[3], value);
      this.infobox = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'infobox' field has been set */
    public boolean hasInfobox() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'infobox' field */
    public gov.pnnl.aristotle.aiminterface.NousAnswerStreamRecord.Builder clearInfobox() {
      infobox = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'profile' field */
    public java.util.List<java.lang.String> getProfile() {
      return profile;
    }
    
    /** Sets the value of the 'profile' field */
    public gov.pnnl.aristotle.aiminterface.NousAnswerStreamRecord.Builder setProfile(java.util.List<java.lang.String> value) {
      validate(fields()[4], value);
      this.profile = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'profile' field has been set */
    public boolean hasProfile() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'profile' field */
    public gov.pnnl.aristotle.aiminterface.NousAnswerStreamRecord.Builder clearProfile() {
      profile = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /** Gets the value of the 'paths' field */
    public java.util.List<java.lang.String> getPaths() {
      return paths;
    }
    
    /** Sets the value of the 'paths' field */
    public gov.pnnl.aristotle.aiminterface.NousAnswerStreamRecord.Builder setPaths(java.util.List<java.lang.String> value) {
      validate(fields()[5], value);
      this.paths = value;
      fieldSetFlags()[5] = true;
      return this; 
    }
    
    /** Checks whether the 'paths' field has been set */
    public boolean hasPaths() {
      return fieldSetFlags()[5];
    }
    
    /** Clears the value of the 'paths' field */
    public gov.pnnl.aristotle.aiminterface.NousAnswerStreamRecord.Builder clearPaths() {
      paths = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /** Gets the value of the 'company' field */
    public java.lang.String getCompany() {
      return company;
    }
    
    /** Sets the value of the 'company' field */
    public gov.pnnl.aristotle.aiminterface.NousAnswerStreamRecord.Builder setCompany(java.lang.String value) {
      validate(fields()[6], value);
      this.company = value;
      fieldSetFlags()[6] = true;
      return this; 
    }
    
    /** Checks whether the 'company' field has been set */
    public boolean hasCompany() {
      return fieldSetFlags()[6];
    }
    
    /** Clears the value of the 'company' field */
    public gov.pnnl.aristotle.aiminterface.NousAnswerStreamRecord.Builder clearCompany() {
      company = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /** Gets the value of the 'lob' field */
    public java.lang.String getLob() {
      return lob;
    }
    
    /** Sets the value of the 'lob' field */
    public gov.pnnl.aristotle.aiminterface.NousAnswerStreamRecord.Builder setLob(java.lang.String value) {
      validate(fields()[7], value);
      this.lob = value;
      fieldSetFlags()[7] = true;
      return this; 
    }
    
    /** Checks whether the 'lob' field has been set */
    public boolean hasLob() {
      return fieldSetFlags()[7];
    }
    
    /** Clears the value of the 'lob' field */
    public gov.pnnl.aristotle.aiminterface.NousAnswerStreamRecord.Builder clearLob() {
      lob = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /** Gets the value of the 'score' field */
    public java.lang.Double getScore() {
      return score;
    }
    
    /** Sets the value of the 'score' field */
    public gov.pnnl.aristotle.aiminterface.NousAnswerStreamRecord.Builder setScore(double value) {
      validate(fields()[8], value);
      this.score = value;
      fieldSetFlags()[8] = true;
      return this; 
    }
    
    /** Checks whether the 'score' field has been set */
    public boolean hasScore() {
      return fieldSetFlags()[8];
    }
    
    /** Clears the value of the 'score' field */
    public gov.pnnl.aristotle.aiminterface.NousAnswerStreamRecord.Builder clearScore() {
      fieldSetFlags()[8] = false;
      return this;
    }

    /** Gets the value of the 'expectedCount' field */
    public java.lang.Long getExpectedCount() {
      return expectedCount;
    }
    
    /** Sets the value of the 'expectedCount' field */
    public gov.pnnl.aristotle.aiminterface.NousAnswerStreamRecord.Builder setExpectedCount(long value) {
      validate(fields()[9], value);
      this.expectedCount = value;
      fieldSetFlags()[9] = true;
      return this; 
    }
    
    /** Checks whether the 'expectedCount' field has been set */
    public boolean hasExpectedCount() {
      return fieldSetFlags()[9];
    }
    
    /** Clears the value of the 'expectedCount' field */
    public gov.pnnl.aristotle.aiminterface.NousAnswerStreamRecord.Builder clearExpectedCount() {
      fieldSetFlags()[9] = false;
      return this;
    }

    /** Gets the value of the 'examplarCompany' field */
    public java.lang.String getExamplarCompany() {
      return examplarCompany;
    }
    
    /** Sets the value of the 'examplarCompany' field */
    public gov.pnnl.aristotle.aiminterface.NousAnswerStreamRecord.Builder setExamplarCompany(java.lang.String value) {
      validate(fields()[10], value);
      this.examplarCompany = value;
      fieldSetFlags()[10] = true;
      return this; 
    }
    
    /** Checks whether the 'examplarCompany' field has been set */
    public boolean hasExamplarCompany() {
      return fieldSetFlags()[10];
    }
    
    /** Clears the value of the 'examplarCompany' field */
    public gov.pnnl.aristotle.aiminterface.NousAnswerStreamRecord.Builder clearExamplarCompany() {
      examplarCompany = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    /** Gets the value of the 'probability' field */
    public java.lang.Double getProbability() {
      return probability;
    }
    
    /** Sets the value of the 'probability' field */
    public gov.pnnl.aristotle.aiminterface.NousAnswerStreamRecord.Builder setProbability(double value) {
      validate(fields()[11], value);
      this.probability = value;
      fieldSetFlags()[11] = true;
      return this; 
    }
    
    /** Checks whether the 'probability' field has been set */
    public boolean hasProbability() {
      return fieldSetFlags()[11];
    }
    
    /** Clears the value of the 'probability' field */
    public gov.pnnl.aristotle.aiminterface.NousAnswerStreamRecord.Builder clearProbability() {
      fieldSetFlags()[11] = false;
      return this;
    }

    /** Gets the value of the 'highScore' field */
    public java.lang.Boolean getHighScore() {
      return highScore;
    }
    
    /** Sets the value of the 'highScore' field */
    public gov.pnnl.aristotle.aiminterface.NousAnswerStreamRecord.Builder setHighScore(boolean value) {
      validate(fields()[12], value);
      this.highScore = value;
      fieldSetFlags()[12] = true;
      return this; 
    }
    
    /** Checks whether the 'highScore' field has been set */
    public boolean hasHighScore() {
      return fieldSetFlags()[12];
    }
    
    /** Clears the value of the 'highScore' field */
    public gov.pnnl.aristotle.aiminterface.NousAnswerStreamRecord.Builder clearHighScore() {
      fieldSetFlags()[12] = false;
      return this;
    }

    /** Gets the value of the 'isHighScore' field */
    public java.lang.Boolean getIsHighScore() {
      return isHighScore;
    }
    
    /** Sets the value of the 'isHighScore' field */
    public gov.pnnl.aristotle.aiminterface.NousAnswerStreamRecord.Builder setIsHighScore(boolean value) {
      validate(fields()[13], value);
      this.isHighScore = value;
      fieldSetFlags()[13] = true;
      return this; 
    }
    
    /** Checks whether the 'isHighScore' field has been set */
    public boolean hasIsHighScore() {
      return fieldSetFlags()[13];
    }
    
    /** Clears the value of the 'isHighScore' field */
    public gov.pnnl.aristotle.aiminterface.NousAnswerStreamRecord.Builder clearIsHighScore() {
      fieldSetFlags()[13] = false;
      return this;
    }

    /** Gets the value of the 'hscodes' field */
    public java.util.List<java.lang.String> getHscodes() {
      return hscodes;
    }
    
    /** Sets the value of the 'hscodes' field */
    public gov.pnnl.aristotle.aiminterface.NousAnswerStreamRecord.Builder setHscodes(java.util.List<java.lang.String> value) {
      validate(fields()[14], value);
      this.hscodes = value;
      fieldSetFlags()[14] = true;
      return this; 
    }
    
    /** Checks whether the 'hscodes' field has been set */
    public boolean hasHscodes() {
      return fieldSetFlags()[14];
    }
    
    /** Clears the value of the 'hscodes' field */
    public gov.pnnl.aristotle.aiminterface.NousAnswerStreamRecord.Builder clearHscodes() {
      hscodes = null;
      fieldSetFlags()[14] = false;
      return this;
    }

    /** Gets the value of the 'recordids' field */
    public java.util.List<java.lang.String> getRecordids() {
      return recordids;
    }
    
    /** Sets the value of the 'recordids' field */
    public gov.pnnl.aristotle.aiminterface.NousAnswerStreamRecord.Builder setRecordids(java.util.List<java.lang.String> value) {
      validate(fields()[15], value);
      this.recordids = value;
      fieldSetFlags()[15] = true;
      return this; 
    }
    
    /** Checks whether the 'recordids' field has been set */
    public boolean hasRecordids() {
      return fieldSetFlags()[15];
    }
    
    /** Clears the value of the 'recordids' field */
    public gov.pnnl.aristotle.aiminterface.NousAnswerStreamRecord.Builder clearRecordids() {
      recordids = null;
      fieldSetFlags()[15] = false;
      return this;
    }


    public NousAnswerStreamRecord build() {
      try {
        NousAnswerStreamRecord record = new NousAnswerStreamRecord();
        record.version = fieldSetFlags()[0] ? this.version : (java.lang.Integer) defaultValue(fields()[0]);
        record.uuid = fieldSetFlags()[1] ? this.uuid : (java.lang.String) defaultValue(fields()[1]);
        record.timestamp = fieldSetFlags()[2] ? this.timestamp : (java.lang.Long) defaultValue(fields()[2]);
        record.infobox = fieldSetFlags()[3] ? this.infobox : (java.lang.String) defaultValue(fields()[3]);
        record.profile = fieldSetFlags()[4] ? this.profile : (java.util.List<java.lang.String>) defaultValue(fields()[4]);
        record.paths = fieldSetFlags()[5] ? this.paths : (java.util.List<java.lang.String>) defaultValue(fields()[5]);
        record.company = fieldSetFlags()[6] ? this.company : (java.lang.String) defaultValue(fields()[6]);
        record.lob = fieldSetFlags()[7] ? this.lob : (java.lang.String) defaultValue(fields()[7]);
        record.score = fieldSetFlags()[8] ? this.score : (java.lang.Double) defaultValue(fields()[8]);
        record.expectedCount = fieldSetFlags()[9] ? this.expectedCount : (java.lang.Long) defaultValue(fields()[9]);
        record.examplarCompany = fieldSetFlags()[10] ? this.examplarCompany : (java.lang.String) defaultValue(fields()[10]);
        record.probability = fieldSetFlags()[11] ? this.probability : (java.lang.Double) defaultValue(fields()[11]);
        record.highScore = fieldSetFlags()[12] ? this.highScore : (java.lang.Boolean) defaultValue(fields()[12]);
        record.isHighScore = fieldSetFlags()[13] ? this.isHighScore : (java.lang.Boolean) defaultValue(fields()[13]);
        record.hscodes = fieldSetFlags()[14] ? this.hscodes : (java.util.List<java.lang.String>) defaultValue(fields()[14]);
        record.recordids = fieldSetFlags()[15] ? this.recordids : (java.util.List<java.lang.String>) defaultValue(fields()[15]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
